services:
  backend:
    build: .
    container_name: tp-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/tradingplatform
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  # frontend:
  #   build: ./frontend
  #   container_name: tp-frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - tp-backend

  mysql:
    container_name: tp-mysql
    image: 'mysql:8.4'
    environment:
      - MYSQL_DATABASE=tradingplatform
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=myuser
    ports:
      - '8889:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 3s
      retries: 30

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: tp-test
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/tradingplatform
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  mysql_data: