name: Run Tests on Push

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker Compose validate
      uses: hoverkraft-tech/compose-action@v2.0.0
      with:
        compose-file: docker-compose.yml

    - name: Docker configuration
      run: docker compose config

    - name: Stop containers
      if: always()
      run: docker-compose down